# .pre-commit-config.yaml

# Pre-commit
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # Use the ref you want to point at
    hooks:
    -   id: check-case-conflict
    -   id: debug-statements
    -   id: check-merge-conflict
    -   id: check-json
    -   id: check-xml
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: double-quote-string-fixer
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: debug-statements
    -   id: no-commit-to-branch
        args:
            - --branch develop
            - --branch master

# flake8
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: flake8
      args: # arguments to configure flake8
        # making isort line length compatible with black
        - "--max-line-length=79"
        - "--max-complexity=18"
        - "--select=B,C,E,F,W,T4,B9"

        # these are errors that will be ignored by flake8
        # check out their meaning here
        # https://flake8.pycqa.org/en/latest/user/error-codes.html
        - "--ignore=E501,W503,F403,E402"

# isort
- repo: https://github.com/asottile/seed-isort-config
  rev: v2.2.0
  hooks:
  - id: seed-isort-config
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.8.0
  hooks:
  - id: isort

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.5.6'  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
